export default [
    { value: 'Dentistry', label: 'Dentistry' },
    { value: 'Pharmacy', label: 'Pharmacy' },
    { value: 'MedicalAnalysis', label: 'Medical Analysis' },
    { value: 'InformationTechnology', label: 'Information Technology' },
    { value: 'Architecture', label: 'Architecture' },
    { value: 'AviationEngineering', label: 'Aviation Engineering' },
    { value: 'MechatronicsEngineering', label: 'Mechatronics Engineering' },
    { value: 'CivilEngineering', label: 'Civil Engineering' },
    { value: 'ComputerEngineering', label: 'Computer Engineering' },
    { value: 'InteriorDesign', label: 'Interior Design' },
    { value: 'PetroleumandMiningEngineering', label: 'Petroleum and Mining Engineering' },
    { value: 'SurveyingandGeomaticsEngineering', label: 'Surveying and Geomatics Engineering' },
    { value: 'Accounting', label: 'Accounting' },
    { value: 'BankingandFinance', label: 'Banking and Finance' },
    { value: 'BusinessandManagement', label: 'Business and Management' },
    { value: 'InternationalRelations&DiplomacyDepartment', label: 'International Relations & Diplomacy Department' },
    { value: 'Law', label: 'Law' },
    { value: 'Nursing', label: 'Nursing' },
    { value: 'BiologyEducation', label: 'Biology Education' },
    { value: 'EnglishLanguageTeaching', label: 'English Language Teaching' },
    { value: 'MathematicsEducation', label: 'Mathematics Education' },
    { value: 'PhysicsEducation', label: 'Physics Education' },
    { value: 'ComputerEducation', label: 'Computer Education' },
    { value: 'LanguagePreparatorySchool', label: 'Language Preparatory School' },
    { value: 'PostgraduateStudies', label: 'Postgraduate Studies' }
]